#!/usr/bin/env bash
#MISE description="Build a release tarball"
#MISE outputs=["build/"]

set -euo pipefail

# TODO: Change this to an environment variable?
VERSION_FILE="VERSION"

VERSION=$(cat $VERSION_FILE)
NAME=$(basename "$(pwd)")
TARBALL="${NAME}-${VERSION}.tar.gz"

# Clean previous build
# Confirm we're in the right place before we start rm'ing stuff.

if [[ -e ./build && -d ./build ]] && ! [[ -L ./build ]]; then
  rm -rf build
  mkdir -p build
fi

# Copy required directories
for dir in bin helpers dependencies prerequisites; do
  cp -a "$dir" build/
done

# Include the VERSION file
cp VERSION build/

# Create the tarball
tar -czf "$TARBALL" -C build .

echo "Release built: $TARBALL"